markdown: kramdown
theme: minima
title: Transylvania Digital Antiques
description: Blog about old maps of Romania
url: "https://iulian-lucaci.github.io"
baseurl: "/transylvania-digital-antiques"
collections:
  posts:
    output: true
    permalink: /:categories/:title
    categories:
    - danube
    - transylvania

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Iulian Lucaci
